configfile: "config_files/config.yaml"

DATASET = config["dataset"]
out_dir = config["output_dir]
salmon_index = config["salmon_index"]
salmon_libtype = config["salmon_libtype"]

(SAMPLES,READS,) = glob_wildcards(DATASET+"/{sample}_{read}.fastq.gz")

rule all:
	input:
		expand(out_dir+"/fastp_filtered_samples/filtered_{sample}_R1.fastq.gz", sample=SAMPLES)
rule fastp:
	input:
		r1 = DATASET+"/{sample}_R1.fastq.gz,
		r2 = DATASET+"/{sample}_R2.fastq.gz
	output:
		r1 = out_dir+"/fastp_filtered_samples/filtered_{sample}_R1.fastq.gz,
		r2 = out_dir+"/fastp_filtered_samples/filtered_{sample}_R2.fastq.gz

rule salmon:
	input:
		r1 = out_dir+"/fastp_filtered_samples/filtered_{sample}_R1.fastq.gz,
		r2 = out_dir+"/fastp_filtered_samples/filtered_{sample}_R2.fastq.gz
	params:
		salmon_index = salmon_index,
		salmon_results_dir = out_dir+"/salmon_results/{sample}_salmon_transcripts_quant"
		libtype = salmon_libtype
	threads: 1
	resources:
		mem_mb = 30000
	output:
		out_dir+"/salmon_results/{sample}_salmon_transcripts_quant/quant.sf"
	shell:
		'''
		salmon quant -i {params.salmon_index} -l {params.libtype} -1 {input.r1} -2 {input.r2} --validateMappings --seqBias --gcBias --threads 1 -o {params.salmon_results_dir}
		'''
